name: validate

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: install terraform
        uses: hashicorp/setup-terraform@v3.1.2
      - name: install tflint
        uses: terraform-linters/setup-tflint@v6.2.1
        with:
          github-token: ${{ secrets.TFLINT_GITHUB_TOKEN }}
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: terraform format
        run: terraform fmt -check -diff -recursive
      - name: terraform lint
        run: |
          tflint --version
          tflint --init
          tflint --config="$(pwd)/.tflint.hcl" --format=compact --recursive
